insert into calc_modules (name, power, outsourced, used, company_id) values ("blanszownik cabinplant", "14.1", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("blanszownik jorgensen", "1.1", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("blanszownik mega", "5.69", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("detektor metali loma", "0.37", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("detektor metali mesutronik", "0.37", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("detektor metali nloma", "0.37", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("formierka", "15.8", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("glazurownik", "0.8", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("hydrotransport sekcja odwadniania", "1.1", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("hydrotransport sekcja pompowania", "5.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("kalibrownik kołowy duży", "1.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("kalibrownik rolkowy", "2.25", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("kosz zasypowy", "1.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("kosz zasypowy", "2.2", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("kosz zasypowy", "4.3", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("kosz zasypowy mega", "4.3", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("krajalnica", "7.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("krajalnica urschel typ dc2110a", "5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("myjka ciśnieniowa tunelu", "2.2", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("naważarki", "0", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("obcinarka końcówek", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("odkamieniacz", "12", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("odpiaszczarka", "0", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("owijarka", "1.3", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("plastrownica fam", "4", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik", "1.1", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik głeboki na kalibrownik", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na blanszownik mega nr", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na brykieciarkę jorgensen", "1.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na formierkę jorgensen", "1.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na obcinarki", "2.2", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na przesiewacz", "2.2", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na płuczki", "1.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na rozrywarkę", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na sorter", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na tunel", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na tunel dt", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na tunel mt", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na tunel zamrażalniczy dt", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na tunel zamrażalniczy mt", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik na wialnię", "2.2", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik nr 14", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik typu z na rozrywarkę", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik typu z nr 15", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik typu z", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("podajnik wibracyjny", "0.9", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("przesiewacz", "1.8", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("płuczka - glazurownik", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("płuczka", "12", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("płuczka flotacyjna do fasoli", "6.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("płuczka kaskadowa", "79.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("płuczka szczotkowa", "0.37", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("płuczka wenecka 1", "79.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("płuczka wenecka 2", "79.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("płuczka wibracyjna", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("rozrywarka", "1.1", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("separator", "2.6", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("sorter", "4.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("stół wibracyjny - rozdzielacz", "1.9", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("stół wibracyjny dwustopniowy", "12", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("stół wibracyjny na blanszownik jorgensen", "0.8", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("stół wibracyjny na krajalnicę fam", "1.4", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("tasma inspekcyjna 5", "1.1", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("tasma inspekcyjna nr 17", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma - odrzut", "1.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma - wyrób gotowy", "1.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna 1", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna 2", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna 3", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna 4", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna nr", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna nr 1", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna n 1", "1.1", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna nr 12", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna nr 16", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna nr 17", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna nr 2", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna nr 6", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma inspekcyjna nr 7", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma krótka nr 11", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma na blanszownik", "0.37", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma nr 16", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma nr 3", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma odbierajaca", "0", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma odbierająca", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma odbierająca krótka nr 11", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma odbierająca nr 12", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma odbierająca nr 7", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma odbierająca odpad", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma odbierająca odrzut", "1.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma odbierająca wyrób gotowy", "1.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma odbirająca odpad", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma odciskająca", "1.1", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma podająca na tunel", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma rozprowadzająca", "0.37", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma transportowa", "0.75", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma transportowa 1", "1.1", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma transportowa 2", "1.5", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma za blanszownikiem nr 9", "0", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma za blanszownikiem nr 9", "0.37", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("taśma za blanszownikiem nr 9", "0.55", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("tunel gyrofreeze", "34", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("tunel zamrażalniczy dt", "128.4", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("tunel zamrażalniczy mt", "110.4", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("wialnia", "11", TRUE, FALSE, NULL);
insert into calc_modules (name, power, outsourced, used, company_id) values ("żmijka", "2.2", TRUE, FALSE, NULL);
