insert into calc_modules(name, power, outsourced, used) values("blanszownik cabinplant", "14.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("blanszownik jorgensen", "1.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("blanszownik mega", "5.69", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("detektor metali loma", "0.37", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("detektor metali mesutronik", "0.37", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("detektor metali nloma", "0.37", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("drylownica pigo nr 1", "6.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("drylownica pigo nr 2", "6.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("drylownica pigo nr 3", "6.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("formierka", "15.8", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("glazurownik", "0.8", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("hydrotransport sekcja odwadniania", "1.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("hydrotransport sekcja pompowania", "5.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("kalibrownik bębnowy duży", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("kalibrownik kołowy duży", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("kalibrownik rolkowy", "2.25", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("komora dynamiczna", "0", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("kosz zasypowy", "0", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("kosz zasypowy", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("kosz zasypowy", "2.2", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("kosz zasypowy", "4.3", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("kosz zasypowy mega", "4.3", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("krajalnica", "7.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("krajalnica urschel typ dc2110a", "5.0", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("myjka ciśnieniowa tunelu", "2.2", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("naważarki", "0", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("obcinarka końcówek", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("ocieraczka hed", "3.0", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("odkamieniacz", "12", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("odpiaszczarka", "0", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("opodajnik na sorter", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("owijarka", "1.3", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("plastrownica fam", "4", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik", "1.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik głeboki na kalibrownik", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik głęboki", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na blanszownik mega", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na brykieciarkę (jorgensen)", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na formierkę (jorgensen)", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na kalibrownik rolkowy", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na obcinarki", "2.2", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na przesiewacz", "2.2", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na płuczki", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na płuczkę głeboki", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na rozrywarkę", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na sorter", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na tunel (dt)", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na tunel (mt)", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na tunel", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na tunel dt", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na tunel mt", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na tunel zamrażalniczy (dt)", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na tunel zamrażalniczy (mt)", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik na wialnię", "2.2", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik nr", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik nr 14", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik nr 15", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik typu z", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("podajnik wibracyjny", "0.9", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("przesiewacz", "1.8", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("przesiewacz skako", "1.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("płuczka - glazurownik", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("płuczka", "12", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("płuczka flotacyjna do fasoli", "6.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("płuczka flotacyjna do wiśni", "3", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("płuczka kaskadowa", "79.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("płuczka szczotkowa", "0.37", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("płuczka wenecka 1", "79.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("płuczka wenecka 2", "79.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("płuczka wibracyjna", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("rozkruszarka", "5.2", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("rozrywarka", "1.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("separator", "2.6", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("sorter", "4.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("sorter optyczny", "4.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("stół do ubijania kartonów", "1.3", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("stół wibracyjny - rozdzielacz", "1.9", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("stół wibracyjny dwustopniowy", "12", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("stół wibracyjny na blanszownik jorgensen", "0.8", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("stół wibracyjny- otrząsarka", "6", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("system mycia ciśnieniowego novadan", "4", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("tasma inspekcyjna 5", "1.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("tasma inspekcyjna nr 17", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("tasma inspekcyjna nr 6", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma - odrzut", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma - wyrób gotowy", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna 1", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna 2", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna 3", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna 4", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 1", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 1", "1.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 11", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 12", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 16", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 17", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 18", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 2", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 3", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 6", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 7", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma inspekcyjna nr 9", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma krótka nr 11", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma na blanszownik", "0.37", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma nr 16", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma nr 3", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma odbierajaca", "0", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma odbierająca - odrzut", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma odbierająca - wyrób gotowy", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma odbierająca", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma odbierająca krótka nr 11", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma odbierająca n 12", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma odbierająca nr 7 ", ".75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma odbierająca odpad", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma odciskająca", "1.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma podajaca na tunel", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma podająca na tunel", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma rozprowadzająca", "0.37", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma transportowa", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma transportowa 1", "1.1", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma transportowa 2", "1.5", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma za blanszownikiem nr 9", "0.37", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśma za blanszownikiem nr 9", "0.55", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("taśna odbieająca nr 12", "0.75", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("tunel gyrofreeze", "34", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("tunel zamrażalniczy (dt)", "128.4", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("tunel zamrażalniczy (mt)", "110.4", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("tunel zamrażalniczy dt", "128.4", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("tunel zamrażalniczy mt", "110.4", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("wialnia", "11", TRUE, FALSE);
insert into calc_modules(name, power, outsourced, used) values("żmijka", "2.2", TRUE, FALSE);