insert into calc_vegetables(name) values("brokuł");
insert into calc_vegetables(name) values("cebula kostka");
insert into calc_vegetables(name) values("cebula plastry");
insert into calc_vegetables(name) values("fasola szparagowa cała");
insert into calc_vegetables(name) values("fasola szparagowa cięta");
insert into calc_vegetables(name) values("fasola ziarno");
insert into calc_vegetables(name) values("groszek");
insert into calc_vegetables(name) values("kalafior");
insert into calc_vegetables(name) values("szpinak całe liście");
insert into calc_vegetables(name) values("szpinak rozdrobniony");